web:
  image: binocarlos/moby-counter:latest
  environment:
     - "USE_REDIS_HOST=redis"
     - "affinity:container==app_redis_1"
  links:
    - redis
  ports:
    - "80:80"
redis:
  image: redis:latest
  environment:
     - "constraint:node==node2"
  volume_driver: flocker
  volumes:
     - 'demo:/data'
